hover_thrust: 0.5660485756397248
pub_debug: true
enable_preview: true
tau_phi: 0.2019288786914721
tau_theta: 0.2005275238237479
tau_psi: 0.8322624658199402
diag_cost_x:
  - 200.0
  - 200.0
  - 200.0
  - 30.0
  - 30.0
  - 30.0
  - 10.0
  - 10.0
diag_cost_u:
  - 5000.0
  - 2000.0
  - 2000.0
diag_cost_xn:
  - 60.0
  - 60.0
  - 60.0
  - 30.0
  - 30.0
  - 30.0
  - 10.0
  - 10.0