pub_debug: true
enable_preview: true

# system parameters
hover_thrust: 0.5656428200006485
tau_phi: 0.1742504945971047
tau_theta: 0.1704274688906173
tau_psi: 0.7410010081424614

# costs
diag_cost_x:
  - 60.0
  - 60.0
  - 60.0
  - 30.0
  - 30.0
  - 30.0
  - 10.0
  - 10.0
diag_cost_u:
  - 50.0
  - 2000.0
  - 2000.0
diag_cost_xn:
  - 60.0
  - 60.0
  - 60.0
  - 30.0
  - 30.0
  - 30.0
  - 10.0
  - 10.0